 version: '3.1'
 services:
     nginx:
         image: nginx:1.13.7
         container_name: nginx
         depends_on:
             - lefvou_project
         volumes:
             - ./nginx.conf:/etc/nginx/conf.d/default.conf
         networks:
             - my-network
         ports:
             - 80:80

     lefvou_project:
         image: lefvou/lefvou_project
         container_name: lefvou_project
         environment:
             - ./app.py
         networks:
             my-network:
                 aliases:
                     - flask-app
         

 networks:
    my-network: